ADJUST_CENTER_LINE = 0
CROSSHAIR_WEIGHT = 2

THETA_MOUNT = 40
THETA_FOV = 69
HOOP_HEIGHT = 3.05
CAMERA_HEIGHT = 0.55
LAUNCH_HEIGHT = 0.97
BASKETBALL_MASS = 0.62
LAUNCH_ENERGY_TRANSFER = .223
#LAUNCH_ENERGY_TRANSFER = .219273
WHEEL_INERTIA = 0.006915

TEXT_WEIGHT = 2
TEXT_SIZE = 2
TEXT_COLOR = (0, 0, 0)
TEXT_LOCATION = 900
DATA_LOCATION = 1600

START_POINT = 150

RPM_DIFFERENCE = 300
DISTANCE_LOCATION = START_POINT
CALCULATED_RPM_LOCATION = START_POINT + 100
DESIRED_AVG_RPM_LOCATION = START_POINT + 200
DESIRED_TOP_RPM_LOCATION = START_POINT + 300
DESIRED_BOTTOM_RPM_LOCATION = START_POINT + 400
ACTUAL_TOP_RPM_LOCATION = START_POINT + 500
ACTUAL_BOTTOM_RPM_LOCATION = START_POINT + 600
DESIRED_ANGLE_LOCATION = START_POINT + 700
ACTUAL_ANGLE_LOCATION = START_POINT + 800




